[package]
name = "aa-sdk-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.2"
tokio = { version = "1", features = ["full", "test-util"] }
async-trait = "0.1"
thiserror = "1"
serde = "1"
serde_json = "1"
url = "2.1"